### ISSUE TITLE
50 errors on startup

### ISSUE THREAD

**Issue by Smitty010** [mProjectsCode/obsidian-meta-bind-plugin#426]
### Please fill out these Check-boxes

- [X] I checked for existing similar issues
- [X] I checked that the plugin is up to date
- [ ] The issue persists with all other plugins and themes disabled

### Plugin Version

1.2.0

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Debug Info

```text
SYSTEM INFO:
	Obsidian version: v1.7.3
	Installer version: v1.6.5
	Operating system: Windows 11 Pro 10.0.22631
	Login status: logged in
	Language: en
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: light
	Community theme: Primary v2.10.0
	Snippets enabled: 16
	Restricted mode: off
	Plugins installed: 105
	Plugins enabled: 65
		1: Tasks v7.10.2
		2: Templater v2.7.3
		3: Calendar v1.5.10
		4: Kanban v2.0.51
		5: Excalidraw v2.5.1
		6: Outliner v4.8.1
		7: Natural Language Dates v0.6.2
		8: QuickAdd v1.11.1
		9: Periodic Notes v0.0.17
		10: Homepage v4.0.6
		11: Minimal Theme Settings v8.1.1
		12: Note Refactor v1.8.2
		13: Recent Files v1.6.0
		14: Spaced Repetition v1.12.8
		15: Style Settings v1.0.9
		16: Workspaces Plus v0.3.3
		17: Tag Wrangler v0.6.1
		18: Hotkeys++ v0.2.7
		19: Fullscreen mode plugin v0.1.2
		20: Projects v1.17.4
		21: Plugin Update Tracker v1.5.2
		22: Open vault in VSCode v1.2.3
		23: Grandfather v1.0.1
		24: No dupe leaves v0.0.12
		25: Callout Manager v1.1.0
		26: Quiet Outline v0.3.36
		27: Linter v1.26.0
		28: MySnippets v1.2.3
		29: Auto Link Title v1.5.4
		30: Status Bar Pomodoro Timer v0.1.14
		31: Advanced URI v1.44.1
		32: Update time on edit v2.4.0
		33: Metadata Menu v0.8.7
		34: Scroll to Top v2.1.4
		35: Supercharged Links v0.12.1
		36: Dataview v0.5.67
		37: Sort Frontmatter v1.0.24
		38: Charts v3.9.0
		39: Quick Switcher++ v4.6.0
		40: Editing Toolbar v2.4.16
		41: Settings Search v1.3.10
		42: Gemini Assistant v1.0.4
		43: Beautitab v1.6.1
		44: Omnisearch v1.24.1
		45: Meta Bind v1.2.0
		46: Text Extractor v0.5.2
		47: Advanced Canvas v3.1.0
		48: Canvas minimap v1.0.15
		49: File Cooker v1.9.0
		50: Commander v0.5.1
		51: Sortable v0.3.1
		52: Banners v1.3.3
		53: Copy as source v1.0.2
		54: Advanced Tables v0.22.0
		55: Footnote Shortcut v0.1.3
		56: Text Generator v0.7.41
		57: Admonition v10.3.2
		58: Highlightr v1.2.2
		59: Modal forms v1.52.0
		60: CardBoard v0.7.9
		61: CSS Inlay Colors v1.1.0
		62: Block Link Plus v1.0.4
		63: Text Format v3.1.0
		64: Lazy Plugin Loader v1.0.18
		65: File Explorer Note Count v1.2.2
```

### Describe the Issue

I get about 50 of these when I start up:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'SecondBrain/FileClass')
    at FileClassFolderButton.addButton (plugin:metadata-menu:25423:44)
    at eval (plugin:metadata-menu:25413:14)
    at e.tryTrigger (app.js:1:722881)
    at e.trigger (app.js:1:722814)
    at t.trigger (app.js:1:2027977)
    at FieldIndex.fullIndex (plugin:metadata-menu:23929:35)
    at async eval (plugin:metadata-menu:23866:9)
```

The directory referred to is where the class files are for my "metadata bind"

### Steps to Reproduce

Just start up the code and look at the developer window

### Expected Behavior

Shouldn't throw that many errors.  It still works, so maybe it's benign.  But I never like exceptions in my code, benign or otherwise

**Comment by mProjectsCode** [comment]
The error stack trace points to the metadata menu plugin and not meta bind.

**Comment by Smitty010** [comment]
Sorry

**Comment by mProjectsCode** [comment]
You should open an issue on metadata menus repo and I would recommend checking if this issue persists with only metadata menu enabled or if it's some other plugin causing problems for metadata menu.

**Comment by Smitty010** [comment]
I have already opened an issue on Metadata menu
